# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-12 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
